package com.joinwe.carcloud.mapper;

import com.joinwe.carcloud.model.Company;
import com.joinwe.carcloud.model.CompanyExample;
import com.joinwe.carcloud.model.CompanyWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    long countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int insert(CompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int insertSelective(CompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    List<CompanyWithBLOBs> selectByExampleWithBLOBsWithRowbounds(CompanyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    List<CompanyWithBLOBs> selectByExampleWithBLOBs(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    List<Company> selectByExampleWithRowbounds(CompanyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    CompanyWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") CompanyWithBLOBs record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") CompanyWithBLOBs record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByPrimaryKeySelective(CompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(CompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByPrimaryKey(Company record);
}