package com.joinwe.carcloud.mapper;

import com.joinwe.carcloud.model.MenuitemIndex;
import com.joinwe.carcloud.model.MenuitemIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MenuitemIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    long countByExample(MenuitemIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int deleteByExample(MenuitemIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int insert(MenuitemIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int insertSelective(MenuitemIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    List<MenuitemIndex> selectByExampleWithRowbounds(MenuitemIndexExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    List<MenuitemIndex> selectByExample(MenuitemIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    MenuitemIndex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") MenuitemIndex record, @Param("example") MenuitemIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByExample(@Param("record") MenuitemIndex record, @Param("example") MenuitemIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByPrimaryKeySelective(MenuitemIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByPrimaryKey(MenuitemIndex record);
}