package com.joinwe.carcloud.mapper;

import com.joinwe.carcloud.model.MenuIndex;
import com.joinwe.carcloud.model.MenuIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MenuIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    long countByExample(MenuIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int deleteByExample(MenuIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int insert(MenuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int insertSelective(MenuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    List<MenuIndex> selectByExampleWithRowbounds(MenuIndexExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    List<MenuIndex> selectByExample(MenuIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    MenuIndex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") MenuIndex record, @Param("example") MenuIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByExample(@Param("record") MenuIndex record, @Param("example") MenuIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByPrimaryKeySelective(MenuIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    int updateByPrimaryKey(MenuIndex record);
}