package com.joinwe.carcloud.mapper;

import com.joinwe.carcloud.model.ServiceItem;
import com.joinwe.carcloud.model.ServiceItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ServiceItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    long countByExample(ServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int deleteByExample(ServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int insert(ServiceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int insertSelective(ServiceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    List<ServiceItem> selectByExampleWithRowbounds(ServiceItemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    List<ServiceItem> selectByExample(ServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    ServiceItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") ServiceItem record, @Param("example") ServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int updateByExample(@Param("record") ServiceItem record, @Param("example") ServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int updateByPrimaryKeySelective(ServiceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_item
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int updateByPrimaryKey(ServiceItem record);
}