package com.joinwe.carcloud.mapper;

import com.joinwe.carcloud.model.UserCompanyFollow;
import com.joinwe.carcloud.model.UserCompanyFollowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserCompanyFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    long countByExample(UserCompanyFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    int deleteByExample(UserCompanyFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    int insert(UserCompanyFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    int insertSelective(UserCompanyFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    List<UserCompanyFollow> selectByExampleWithRowbounds(UserCompanyFollowExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    List<UserCompanyFollow> selectByExample(UserCompanyFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    UserCompanyFollow selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserCompanyFollow record, @Param("example") UserCompanyFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    int updateByExample(@Param("record") UserCompanyFollow record, @Param("example") UserCompanyFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    int updateByPrimaryKeySelective(UserCompanyFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_company_follow
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    int updateByPrimaryKey(UserCompanyFollow record);
}