package com.joinwe.carcloud.mapper;

import com.joinwe.carcloud.model.WebUser;
import com.joinwe.carcloud.model.WebUserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface WebUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    long countByExample(WebUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int deleteByExample(WebUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int insert(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int insertSelective(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    List<WebUser> selectByExampleWithRowbounds(WebUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    List<WebUser> selectByExample(WebUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    WebUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") WebUser record, @Param("example") WebUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int updateByExample(@Param("record") WebUser record, @Param("example") WebUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int updateByPrimaryKeySelective(WebUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_user
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    int updateByPrimaryKey(WebUser record);
}