package com.joinwe.carcloud.model;

import java.util.Date;

public class CompanyType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.name
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.cover
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.sort
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long editorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_type.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.id
     *
     * @return the value of company_type.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.id
     *
     * @param id the value for company_type.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.name
     *
     * @return the value of company_type.name
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.name
     *
     * @param name the value for company_type.name
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.cover
     *
     * @return the value of company_type.cover
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.cover
     *
     * @param cover the value for company_type.cover
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.sort
     *
     * @return the value of company_type.sort
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.sort
     *
     * @param sort the value for company_type.sort
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.gmt_create
     *
     * @return the value of company_type.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.gmt_create
     *
     * @param gmtCreate the value for company_type.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.creatorid
     *
     * @return the value of company_type.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.creatorid
     *
     * @param creatorid the value for company_type.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.gmt_modified
     *
     * @return the value of company_type.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.gmt_modified
     *
     * @param gmtModified the value for company_type.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.editorid
     *
     * @return the value of company_type.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.editorid
     *
     * @param editorid the value for company_type.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setEditorid(Long editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.is_deleted
     *
     * @return the value of company_type.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.is_deleted
     *
     * @param isDeleted the value for company_type.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.is_locked
     *
     * @return the value of company_type.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.is_locked
     *
     * @param isLocked the value for company_type.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_type.version
     *
     * @return the value of company_type.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_type.version
     *
     * @param version the value for company_type.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}