package com.joinwe.carcloud.model;

import java.math.BigDecimal;
import java.util.Date;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.bussinesstypeid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String bussinesstypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.bussinesstypename
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String bussinesstypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.cover
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.service_time
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String serviceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.tel
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.province
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.city
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.district
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.longitude
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.latitude
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long editorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.bussinesstypeid
     *
     * @return the value of company.bussinesstypeid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getBussinesstypeid() {
        return bussinesstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.bussinesstypeid
     *
     * @param bussinesstypeid the value for company.bussinesstypeid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setBussinesstypeid(String bussinesstypeid) {
        this.bussinesstypeid = bussinesstypeid == null ? null : bussinesstypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.bussinesstypename
     *
     * @return the value of company.bussinesstypename
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getBussinesstypename() {
        return bussinesstypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.bussinesstypename
     *
     * @param bussinesstypename the value for company.bussinesstypename
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setBussinesstypename(String bussinesstypename) {
        this.bussinesstypename = bussinesstypename == null ? null : bussinesstypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.cover
     *
     * @return the value of company.cover
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.cover
     *
     * @param cover the value for company.cover
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.service_time
     *
     * @return the value of company.service_time
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getServiceTime() {
        return serviceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.service_time
     *
     * @param serviceTime the value for company.service_time
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setServiceTime(String serviceTime) {
        this.serviceTime = serviceTime == null ? null : serviceTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.tel
     *
     * @return the value of company.tel
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.tel
     *
     * @param tel the value for company.tel
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.province
     *
     * @return the value of company.province
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.province
     *
     * @param province the value for company.province
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.city
     *
     * @return the value of company.city
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.city
     *
     * @param city the value for company.city
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.district
     *
     * @return the value of company.district
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.district
     *
     * @param district the value for company.district
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.longitude
     *
     * @return the value of company.longitude
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.longitude
     *
     * @param longitude the value for company.longitude
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.latitude
     *
     * @return the value of company.latitude
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.latitude
     *
     * @param latitude the value for company.latitude
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.gmt_create
     *
     * @return the value of company.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.gmt_create
     *
     * @param gmtCreate the value for company.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.creatorid
     *
     * @return the value of company.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.creatorid
     *
     * @param creatorid the value for company.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.gmt_modified
     *
     * @return the value of company.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.gmt_modified
     *
     * @param gmtModified the value for company.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.editorid
     *
     * @return the value of company.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.editorid
     *
     * @param editorid the value for company.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setEditorid(Long editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.is_deleted
     *
     * @return the value of company.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.is_deleted
     *
     * @param isDeleted the value for company.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.is_locked
     *
     * @return the value of company.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.is_locked
     *
     * @param isLocked the value for company.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.version
     *
     * @return the value of company.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.version
     *
     * @param version the value for company.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}