package com.joinwe.carcloud.model;

import java.util.Date;

public class FinanceSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.type
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.realid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long realid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.voucherindex
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long voucherindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long editorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_subject.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.id
     *
     * @return the value of finance_subject.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.id
     *
     * @param id the value for finance_subject.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.type
     *
     * @return the value of finance_subject.type
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.type
     *
     * @param type the value for finance_subject.type
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.realid
     *
     * @return the value of finance_subject.realid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getRealid() {
        return realid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.realid
     *
     * @param realid the value for finance_subject.realid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setRealid(Long realid) {
        this.realid = realid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.voucherindex
     *
     * @return the value of finance_subject.voucherindex
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getVoucherindex() {
        return voucherindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.voucherindex
     *
     * @param voucherindex the value for finance_subject.voucherindex
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setVoucherindex(Long voucherindex) {
        this.voucherindex = voucherindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.gmt_create
     *
     * @return the value of finance_subject.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.gmt_create
     *
     * @param gmtCreate the value for finance_subject.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.creatorid
     *
     * @return the value of finance_subject.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.creatorid
     *
     * @param creatorid the value for finance_subject.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.gmt_modified
     *
     * @return the value of finance_subject.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.gmt_modified
     *
     * @param gmtModified the value for finance_subject.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.editorid
     *
     * @return the value of finance_subject.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.editorid
     *
     * @param editorid the value for finance_subject.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setEditorid(Long editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.is_deleted
     *
     * @return the value of finance_subject.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.is_deleted
     *
     * @param isDeleted the value for finance_subject.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.is_locked
     *
     * @return the value of finance_subject.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.is_locked
     *
     * @param isLocked the value for finance_subject.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_subject.version
     *
     * @return the value of finance_subject.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_subject.version
     *
     * @param version the value for finance_subject.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}