package com.joinwe.carcloud.model;

import java.util.Date;

public class MenuitemIndex {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.menuid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.menuitemname
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String menuitemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.menuitemicon
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String menuitemicon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.menuitemorder
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long menuitemorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.menuitemurl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String menuitemurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.menuitemrouteurl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String menuitemrouteurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.menuitemctrl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String menuitemctrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.menuitemparentid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long menuitemparentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.isshow
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long editorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Boolean isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menuitem_index.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.id
     *
     * @return the value of menuitem_index.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.id
     *
     * @param id the value for menuitem_index.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.menuid
     *
     * @return the value of menuitem_index.menuid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.menuid
     *
     * @param menuid the value for menuitem_index.menuid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setMenuid(Long menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.menuitemname
     *
     * @return the value of menuitem_index.menuitemname
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getMenuitemname() {
        return menuitemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.menuitemname
     *
     * @param menuitemname the value for menuitem_index.menuitemname
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setMenuitemname(String menuitemname) {
        this.menuitemname = menuitemname == null ? null : menuitemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.menuitemicon
     *
     * @return the value of menuitem_index.menuitemicon
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getMenuitemicon() {
        return menuitemicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.menuitemicon
     *
     * @param menuitemicon the value for menuitem_index.menuitemicon
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setMenuitemicon(String menuitemicon) {
        this.menuitemicon = menuitemicon == null ? null : menuitemicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.menuitemorder
     *
     * @return the value of menuitem_index.menuitemorder
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getMenuitemorder() {
        return menuitemorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.menuitemorder
     *
     * @param menuitemorder the value for menuitem_index.menuitemorder
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setMenuitemorder(Long menuitemorder) {
        this.menuitemorder = menuitemorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.menuitemurl
     *
     * @return the value of menuitem_index.menuitemurl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getMenuitemurl() {
        return menuitemurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.menuitemurl
     *
     * @param menuitemurl the value for menuitem_index.menuitemurl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setMenuitemurl(String menuitemurl) {
        this.menuitemurl = menuitemurl == null ? null : menuitemurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.menuitemrouteurl
     *
     * @return the value of menuitem_index.menuitemrouteurl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getMenuitemrouteurl() {
        return menuitemrouteurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.menuitemrouteurl
     *
     * @param menuitemrouteurl the value for menuitem_index.menuitemrouteurl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setMenuitemrouteurl(String menuitemrouteurl) {
        this.menuitemrouteurl = menuitemrouteurl == null ? null : menuitemrouteurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.menuitemctrl
     *
     * @return the value of menuitem_index.menuitemctrl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getMenuitemctrl() {
        return menuitemctrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.menuitemctrl
     *
     * @param menuitemctrl the value for menuitem_index.menuitemctrl
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setMenuitemctrl(String menuitemctrl) {
        this.menuitemctrl = menuitemctrl == null ? null : menuitemctrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.menuitemparentid
     *
     * @return the value of menuitem_index.menuitemparentid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getMenuitemparentid() {
        return menuitemparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.menuitemparentid
     *
     * @param menuitemparentid the value for menuitem_index.menuitemparentid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setMenuitemparentid(Long menuitemparentid) {
        this.menuitemparentid = menuitemparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.isshow
     *
     * @return the value of menuitem_index.isshow
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.isshow
     *
     * @param isshow the value for menuitem_index.isshow
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsshow(Boolean isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.gmt_create
     *
     * @return the value of menuitem_index.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.gmt_create
     *
     * @param gmtCreate the value for menuitem_index.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.creatorid
     *
     * @return the value of menuitem_index.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.creatorid
     *
     * @param creatorid the value for menuitem_index.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.gmt_modified
     *
     * @return the value of menuitem_index.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.gmt_modified
     *
     * @param gmtModified the value for menuitem_index.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.editorid
     *
     * @return the value of menuitem_index.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.editorid
     *
     * @param editorid the value for menuitem_index.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setEditorid(Long editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.is_deleted
     *
     * @return the value of menuitem_index.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.is_deleted
     *
     * @param isDeleted the value for menuitem_index.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.is_locked
     *
     * @return the value of menuitem_index.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.is_locked
     *
     * @param isLocked the value for menuitem_index.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menuitem_index.version
     *
     * @return the value of menuitem_index.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menuitem_index.version
     *
     * @param version the value for menuitem_index.version
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}