package com.joinwe.carcloud.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MenuitemIndexExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public MenuitemIndexExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNull() {
            addCriterion("menuid is null");
            return (Criteria) this;
        }

        public Criteria andMenuidIsNotNull() {
            addCriterion("menuid is not null");
            return (Criteria) this;
        }

        public Criteria andMenuidEqualTo(Long value) {
            addCriterion("menuid =", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotEqualTo(Long value) {
            addCriterion("menuid <>", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThan(Long value) {
            addCriterion("menuid >", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidGreaterThanOrEqualTo(Long value) {
            addCriterion("menuid >=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThan(Long value) {
            addCriterion("menuid <", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidLessThanOrEqualTo(Long value) {
            addCriterion("menuid <=", value, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidIn(List<Long> values) {
            addCriterion("menuid in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotIn(List<Long> values) {
            addCriterion("menuid not in", values, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidBetween(Long value1, Long value2) {
            addCriterion("menuid between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuidNotBetween(Long value1, Long value2) {
            addCriterion("menuid not between", value1, value2, "menuid");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameIsNull() {
            addCriterion("menuitemname is null");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameIsNotNull() {
            addCriterion("menuitemname is not null");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameEqualTo(String value) {
            addCriterion("menuitemname =", value, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameNotEqualTo(String value) {
            addCriterion("menuitemname <>", value, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameGreaterThan(String value) {
            addCriterion("menuitemname >", value, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameGreaterThanOrEqualTo(String value) {
            addCriterion("menuitemname >=", value, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameLessThan(String value) {
            addCriterion("menuitemname <", value, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameLessThanOrEqualTo(String value) {
            addCriterion("menuitemname <=", value, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameLike(String value) {
            addCriterion("menuitemname like", value, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameNotLike(String value) {
            addCriterion("menuitemname not like", value, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameIn(List<String> values) {
            addCriterion("menuitemname in", values, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameNotIn(List<String> values) {
            addCriterion("menuitemname not in", values, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameBetween(String value1, String value2) {
            addCriterion("menuitemname between", value1, value2, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemnameNotBetween(String value1, String value2) {
            addCriterion("menuitemname not between", value1, value2, "menuitemname");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconIsNull() {
            addCriterion("menuitemicon is null");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconIsNotNull() {
            addCriterion("menuitemicon is not null");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconEqualTo(String value) {
            addCriterion("menuitemicon =", value, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconNotEqualTo(String value) {
            addCriterion("menuitemicon <>", value, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconGreaterThan(String value) {
            addCriterion("menuitemicon >", value, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconGreaterThanOrEqualTo(String value) {
            addCriterion("menuitemicon >=", value, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconLessThan(String value) {
            addCriterion("menuitemicon <", value, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconLessThanOrEqualTo(String value) {
            addCriterion("menuitemicon <=", value, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconLike(String value) {
            addCriterion("menuitemicon like", value, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconNotLike(String value) {
            addCriterion("menuitemicon not like", value, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconIn(List<String> values) {
            addCriterion("menuitemicon in", values, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconNotIn(List<String> values) {
            addCriterion("menuitemicon not in", values, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconBetween(String value1, String value2) {
            addCriterion("menuitemicon between", value1, value2, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemiconNotBetween(String value1, String value2) {
            addCriterion("menuitemicon not between", value1, value2, "menuitemicon");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderIsNull() {
            addCriterion("menuitemorder is null");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderIsNotNull() {
            addCriterion("menuitemorder is not null");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderEqualTo(Long value) {
            addCriterion("menuitemorder =", value, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderNotEqualTo(Long value) {
            addCriterion("menuitemorder <>", value, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderGreaterThan(Long value) {
            addCriterion("menuitemorder >", value, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderGreaterThanOrEqualTo(Long value) {
            addCriterion("menuitemorder >=", value, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderLessThan(Long value) {
            addCriterion("menuitemorder <", value, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderLessThanOrEqualTo(Long value) {
            addCriterion("menuitemorder <=", value, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderIn(List<Long> values) {
            addCriterion("menuitemorder in", values, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderNotIn(List<Long> values) {
            addCriterion("menuitemorder not in", values, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderBetween(Long value1, Long value2) {
            addCriterion("menuitemorder between", value1, value2, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemorderNotBetween(Long value1, Long value2) {
            addCriterion("menuitemorder not between", value1, value2, "menuitemorder");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlIsNull() {
            addCriterion("menuitemurl is null");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlIsNotNull() {
            addCriterion("menuitemurl is not null");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlEqualTo(String value) {
            addCriterion("menuitemurl =", value, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlNotEqualTo(String value) {
            addCriterion("menuitemurl <>", value, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlGreaterThan(String value) {
            addCriterion("menuitemurl >", value, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlGreaterThanOrEqualTo(String value) {
            addCriterion("menuitemurl >=", value, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlLessThan(String value) {
            addCriterion("menuitemurl <", value, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlLessThanOrEqualTo(String value) {
            addCriterion("menuitemurl <=", value, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlLike(String value) {
            addCriterion("menuitemurl like", value, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlNotLike(String value) {
            addCriterion("menuitemurl not like", value, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlIn(List<String> values) {
            addCriterion("menuitemurl in", values, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlNotIn(List<String> values) {
            addCriterion("menuitemurl not in", values, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlBetween(String value1, String value2) {
            addCriterion("menuitemurl between", value1, value2, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemurlNotBetween(String value1, String value2) {
            addCriterion("menuitemurl not between", value1, value2, "menuitemurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlIsNull() {
            addCriterion("menuitemrouteurl is null");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlIsNotNull() {
            addCriterion("menuitemrouteurl is not null");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlEqualTo(String value) {
            addCriterion("menuitemrouteurl =", value, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlNotEqualTo(String value) {
            addCriterion("menuitemrouteurl <>", value, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlGreaterThan(String value) {
            addCriterion("menuitemrouteurl >", value, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlGreaterThanOrEqualTo(String value) {
            addCriterion("menuitemrouteurl >=", value, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlLessThan(String value) {
            addCriterion("menuitemrouteurl <", value, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlLessThanOrEqualTo(String value) {
            addCriterion("menuitemrouteurl <=", value, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlLike(String value) {
            addCriterion("menuitemrouteurl like", value, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlNotLike(String value) {
            addCriterion("menuitemrouteurl not like", value, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlIn(List<String> values) {
            addCriterion("menuitemrouteurl in", values, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlNotIn(List<String> values) {
            addCriterion("menuitemrouteurl not in", values, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlBetween(String value1, String value2) {
            addCriterion("menuitemrouteurl between", value1, value2, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemrouteurlNotBetween(String value1, String value2) {
            addCriterion("menuitemrouteurl not between", value1, value2, "menuitemrouteurl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlIsNull() {
            addCriterion("menuitemctrl is null");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlIsNotNull() {
            addCriterion("menuitemctrl is not null");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlEqualTo(String value) {
            addCriterion("menuitemctrl =", value, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlNotEqualTo(String value) {
            addCriterion("menuitemctrl <>", value, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlGreaterThan(String value) {
            addCriterion("menuitemctrl >", value, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlGreaterThanOrEqualTo(String value) {
            addCriterion("menuitemctrl >=", value, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlLessThan(String value) {
            addCriterion("menuitemctrl <", value, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlLessThanOrEqualTo(String value) {
            addCriterion("menuitemctrl <=", value, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlLike(String value) {
            addCriterion("menuitemctrl like", value, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlNotLike(String value) {
            addCriterion("menuitemctrl not like", value, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlIn(List<String> values) {
            addCriterion("menuitemctrl in", values, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlNotIn(List<String> values) {
            addCriterion("menuitemctrl not in", values, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlBetween(String value1, String value2) {
            addCriterion("menuitemctrl between", value1, value2, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemctrlNotBetween(String value1, String value2) {
            addCriterion("menuitemctrl not between", value1, value2, "menuitemctrl");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidIsNull() {
            addCriterion("menuitemparentid is null");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidIsNotNull() {
            addCriterion("menuitemparentid is not null");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidEqualTo(Long value) {
            addCriterion("menuitemparentid =", value, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidNotEqualTo(Long value) {
            addCriterion("menuitemparentid <>", value, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidGreaterThan(Long value) {
            addCriterion("menuitemparentid >", value, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidGreaterThanOrEqualTo(Long value) {
            addCriterion("menuitemparentid >=", value, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidLessThan(Long value) {
            addCriterion("menuitemparentid <", value, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidLessThanOrEqualTo(Long value) {
            addCriterion("menuitemparentid <=", value, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidIn(List<Long> values) {
            addCriterion("menuitemparentid in", values, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidNotIn(List<Long> values) {
            addCriterion("menuitemparentid not in", values, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidBetween(Long value1, Long value2) {
            addCriterion("menuitemparentid between", value1, value2, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andMenuitemparentidNotBetween(Long value1, Long value2) {
            addCriterion("menuitemparentid not between", value1, value2, "menuitemparentid");
            return (Criteria) this;
        }

        public Criteria andIsshowIsNull() {
            addCriterion("isshow is null");
            return (Criteria) this;
        }

        public Criteria andIsshowIsNotNull() {
            addCriterion("isshow is not null");
            return (Criteria) this;
        }

        public Criteria andIsshowEqualTo(Boolean value) {
            addCriterion("isshow =", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowNotEqualTo(Boolean value) {
            addCriterion("isshow <>", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowGreaterThan(Boolean value) {
            addCriterion("isshow >", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isshow >=", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowLessThan(Boolean value) {
            addCriterion("isshow <", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowLessThanOrEqualTo(Boolean value) {
            addCriterion("isshow <=", value, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowIn(List<Boolean> values) {
            addCriterion("isshow in", values, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowNotIn(List<Boolean> values) {
            addCriterion("isshow not in", values, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowBetween(Boolean value1, Boolean value2) {
            addCriterion("isshow between", value1, value2, "isshow");
            return (Criteria) this;
        }

        public Criteria andIsshowNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isshow not between", value1, value2, "isshow");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNull() {
            addCriterion("creatorid is null");
            return (Criteria) this;
        }

        public Criteria andCreatoridIsNotNull() {
            addCriterion("creatorid is not null");
            return (Criteria) this;
        }

        public Criteria andCreatoridEqualTo(Long value) {
            addCriterion("creatorid =", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotEqualTo(Long value) {
            addCriterion("creatorid <>", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThan(Long value) {
            addCriterion("creatorid >", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridGreaterThanOrEqualTo(Long value) {
            addCriterion("creatorid >=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThan(Long value) {
            addCriterion("creatorid <", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridLessThanOrEqualTo(Long value) {
            addCriterion("creatorid <=", value, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridIn(List<Long> values) {
            addCriterion("creatorid in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotIn(List<Long> values) {
            addCriterion("creatorid not in", values, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridBetween(Long value1, Long value2) {
            addCriterion("creatorid between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andCreatoridNotBetween(Long value1, Long value2) {
            addCriterion("creatorid not between", value1, value2, "creatorid");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andEditoridIsNull() {
            addCriterion("editorid is null");
            return (Criteria) this;
        }

        public Criteria andEditoridIsNotNull() {
            addCriterion("editorid is not null");
            return (Criteria) this;
        }

        public Criteria andEditoridEqualTo(Long value) {
            addCriterion("editorid =", value, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridNotEqualTo(Long value) {
            addCriterion("editorid <>", value, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridGreaterThan(Long value) {
            addCriterion("editorid >", value, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridGreaterThanOrEqualTo(Long value) {
            addCriterion("editorid >=", value, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridLessThan(Long value) {
            addCriterion("editorid <", value, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridLessThanOrEqualTo(Long value) {
            addCriterion("editorid <=", value, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridIn(List<Long> values) {
            addCriterion("editorid in", values, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridNotIn(List<Long> values) {
            addCriterion("editorid not in", values, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridBetween(Long value1, Long value2) {
            addCriterion("editorid between", value1, value2, "editorid");
            return (Criteria) this;
        }

        public Criteria andEditoridNotBetween(Long value1, Long value2) {
            addCriterion("editorid not between", value1, value2, "editorid");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Boolean value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Boolean value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Boolean value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Boolean value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Boolean> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Boolean> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsLockedIsNull() {
            addCriterion("is_locked is null");
            return (Criteria) this;
        }

        public Criteria andIsLockedIsNotNull() {
            addCriterion("is_locked is not null");
            return (Criteria) this;
        }

        public Criteria andIsLockedEqualTo(Boolean value) {
            addCriterion("is_locked =", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotEqualTo(Boolean value) {
            addCriterion("is_locked <>", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedGreaterThan(Boolean value) {
            addCriterion("is_locked >", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_locked >=", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedLessThan(Boolean value) {
            addCriterion("is_locked <", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_locked <=", value, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedIn(List<Boolean> values) {
            addCriterion("is_locked in", values, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotIn(List<Boolean> values) {
            addCriterion("is_locked not in", values, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_locked between", value1, value2, "isLocked");
            return (Criteria) this;
        }

        public Criteria andIsLockedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_locked not between", value1, value2, "isLocked");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table menuitem_index
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 23 19:13:26 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table menuitem_index
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}