package com.joinwe.carcloud.model;

public class OperationWithBLOBs extends Operation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.service
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String service;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.above
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String above;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation.introduced
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private String introduced;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.service
     *
     * @return the value of operation.service
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.service
     *
     * @param service the value for operation.service
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.above
     *
     * @return the value of operation.above
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getAbove() {
        return above;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.above
     *
     * @param above the value for operation.above
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setAbove(String above) {
        this.above = above == null ? null : above.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation.introduced
     *
     * @return the value of operation.introduced
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public String getIntroduced() {
        return introduced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation.introduced
     *
     * @param introduced the value for operation.introduced
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public void setIntroduced(String introduced) {
        this.introduced = introduced == null ? null : introduced.trim();
    }
}