package com.joinwe.carcloud.model;

import java.util.Date;

public class PermissionResourceMap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.permissionid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long permissionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.resourceid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long resourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long editorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Boolean isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionresource_map.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.id
     *
     * @return the value of permissionresource_map.id
     *
     * @mbg.generated Tue Jun 23 19:13:26 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.id
     *
     * @param id the value for permissionresource_map.id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.permissionid
     *
     * @return the value of permissionresource_map.permissionid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.permissionid
     *
     * @param permissionid the value for permissionresource_map.permissionid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setPermissionid(Long permissionid) {
        this.permissionid = permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.resourceid
     *
     * @return the value of permissionresource_map.resourceid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.resourceid
     *
     * @param resourceid the value for permissionresource_map.resourceid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setResourceid(Long resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.gmt_create
     *
     * @return the value of permissionresource_map.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.gmt_create
     *
     * @param gmtCreate the value for permissionresource_map.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.creatorid
     *
     * @return the value of permissionresource_map.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.creatorid
     *
     * @param creatorid the value for permissionresource_map.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.gmt_modified
     *
     * @return the value of permissionresource_map.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.gmt_modified
     *
     * @param gmtModified the value for permissionresource_map.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.editorid
     *
     * @return the value of permissionresource_map.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.editorid
     *
     * @param editorid the value for permissionresource_map.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setEditorid(Long editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.is_deleted
     *
     * @return the value of permissionresource_map.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.is_deleted
     *
     * @param isDeleted the value for permissionresource_map.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.is_locked
     *
     * @return the value of permissionresource_map.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.is_locked
     *
     * @param isLocked the value for permissionresource_map.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionresource_map.version
     *
     * @return the value of permissionresource_map.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionresource_map.version
     *
     * @param version the value for permissionresource_map.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}