package com.joinwe.carcloud.model;

import java.util.Date;

public class ServiceItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.company_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.price
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long editorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Boolean isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_item.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.id
     *
     * @return the value of service_item.id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.id
     *
     * @param id the value for service_item.id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.company_id
     *
     * @return the value of service_item.company_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.company_id
     *
     * @param companyId the value for service_item.company_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.name
     *
     * @return the value of service_item.name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.name
     *
     * @param name the value for service_item.name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.price
     *
     * @return the value of service_item.price
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.price
     *
     * @param price the value for service_item.price
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.gmt_create
     *
     * @return the value of service_item.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.gmt_create
     *
     * @param gmtCreate the value for service_item.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.creatorid
     *
     * @return the value of service_item.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.creatorid
     *
     * @param creatorid the value for service_item.creatorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.gmt_modified
     *
     * @return the value of service_item.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.gmt_modified
     *
     * @param gmtModified the value for service_item.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.editorid
     *
     * @return the value of service_item.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getEditorid() {
        return editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.editorid
     *
     * @param editorid the value for service_item.editorid
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setEditorid(Long editorid) {
        this.editorid = editorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.is_deleted
     *
     * @return the value of service_item.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.is_deleted
     *
     * @param isDeleted the value for service_item.is_deleted
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.is_locked
     *
     * @return the value of service_item.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.is_locked
     *
     * @param isLocked the value for service_item.is_locked
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_item.version
     *
     * @return the value of service_item.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_item.version
     *
     * @param version the value for service_item.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}