package com.joinwe.carcloud.model;

import java.util.Date;

public class UserCompanyFollow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.user_id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.company_id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.company_name
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.company_cover
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private String companyCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.company_province
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private String companyProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.company_city
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private String companyCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.company_district
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private String companyDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.company_address
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private String companyAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.gmt_create
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.gmt_modified
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.status
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.is_deleted
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.is_locked
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Boolean isLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_company_follow.version
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.id
     *
     * @return the value of user_company_follow.id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.id
     *
     * @param id the value for user_company_follow.id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.user_id
     *
     * @return the value of user_company_follow.user_id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.user_id
     *
     * @param userId the value for user_company_follow.user_id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.company_id
     *
     * @return the value of user_company_follow.company_id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.company_id
     *
     * @param companyId the value for user_company_follow.company_id
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.company_name
     *
     * @return the value of user_company_follow.company_name
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.company_name
     *
     * @param companyName the value for user_company_follow.company_name
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.company_cover
     *
     * @return the value of user_company_follow.company_cover
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public String getCompanyCover() {
        return companyCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.company_cover
     *
     * @param companyCover the value for user_company_follow.company_cover
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setCompanyCover(String companyCover) {
        this.companyCover = companyCover == null ? null : companyCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.company_province
     *
     * @return the value of user_company_follow.company_province
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public String getCompanyProvince() {
        return companyProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.company_province
     *
     * @param companyProvince the value for user_company_follow.company_province
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setCompanyProvince(String companyProvince) {
        this.companyProvince = companyProvince == null ? null : companyProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.company_city
     *
     * @return the value of user_company_follow.company_city
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public String getCompanyCity() {
        return companyCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.company_city
     *
     * @param companyCity the value for user_company_follow.company_city
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setCompanyCity(String companyCity) {
        this.companyCity = companyCity == null ? null : companyCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.company_district
     *
     * @return the value of user_company_follow.company_district
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public String getCompanyDistrict() {
        return companyDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.company_district
     *
     * @param companyDistrict the value for user_company_follow.company_district
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setCompanyDistrict(String companyDistrict) {
        this.companyDistrict = companyDistrict == null ? null : companyDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.company_address
     *
     * @return the value of user_company_follow.company_address
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.company_address
     *
     * @param companyAddress the value for user_company_follow.company_address
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.gmt_create
     *
     * @return the value of user_company_follow.gmt_create
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.gmt_create
     *
     * @param gmtCreate the value for user_company_follow.gmt_create
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.gmt_modified
     *
     * @return the value of user_company_follow.gmt_modified
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.gmt_modified
     *
     * @param gmtModified the value for user_company_follow.gmt_modified
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.status
     *
     * @return the value of user_company_follow.status
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.status
     *
     * @param status the value for user_company_follow.status
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.is_deleted
     *
     * @return the value of user_company_follow.is_deleted
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.is_deleted
     *
     * @param isDeleted the value for user_company_follow.is_deleted
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.is_locked
     *
     * @return the value of user_company_follow.is_locked
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Boolean getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.is_locked
     *
     * @param isLocked the value for user_company_follow.is_locked
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setIsLocked(Boolean isLocked) {
        this.isLocked = isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_company_follow.version
     *
     * @return the value of user_company_follow.version
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_company_follow.version
     *
     * @param version the value for user_company_follow.version
     *
     * @mbg.generated Tue May 19 12:03:58 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}