package com.joinwe.carcloud.model;

import java.util.Date;

public class WebUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.avatar_url
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.login_status
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Integer loginStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.token
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.remark
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.login_name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.position
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.password
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.type
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.create_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.editor_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Long editorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_user.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.id
     *
     * @return the value of web_user.id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.id
     *
     * @param id the value for web_user.id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.name
     *
     * @return the value of web_user.name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.name
     *
     * @param name the value for web_user.name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.avatar_url
     *
     * @return the value of web_user.avatar_url
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.avatar_url
     *
     * @param avatarUrl the value for web_user.avatar_url
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.login_status
     *
     * @return the value of web_user.login_status
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Integer getLoginStatus() {
        return loginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.login_status
     *
     * @param loginStatus the value for web_user.login_status
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setLoginStatus(Integer loginStatus) {
        this.loginStatus = loginStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.token
     *
     * @return the value of web_user.token
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.token
     *
     * @param token the value for web_user.token
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.remark
     *
     * @return the value of web_user.remark
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.remark
     *
     * @param remark the value for web_user.remark
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.login_name
     *
     * @return the value of web_user.login_name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.login_name
     *
     * @param loginName the value for web_user.login_name
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.position
     *
     * @return the value of web_user.position
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.position
     *
     * @param position the value for web_user.position
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.password
     *
     * @return the value of web_user.password
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.password
     *
     * @param password the value for web_user.password
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.type
     *
     * @return the value of web_user.type
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.type
     *
     * @param type the value for web_user.type
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.create_id
     *
     * @return the value of web_user.create_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.create_id
     *
     * @param createId the value for web_user.create_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.editor_id
     *
     * @return the value of web_user.editor_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Long getEditorId() {
        return editorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.editor_id
     *
     * @param editorId the value for web_user.editor_id
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setEditorId(Long editorId) {
        this.editorId = editorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.gmt_create
     *
     * @return the value of web_user.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.gmt_create
     *
     * @param gmtCreate the value for web_user.gmt_create
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.gmt_modified
     *
     * @return the value of web_user.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.gmt_modified
     *
     * @param gmtModified the value for web_user.gmt_modified
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_user.version
     *
     * @return the value of web_user.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_user.version
     *
     * @param version the value for web_user.version
     *
     * @mbg.generated Tue Jun 23 19:13:27 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}